AUTINS ; IHS/OIT/FBD&NKD - INSURER RELATED FUNCTIONS ; 07/14/2017
 ;;98.1;IHS DICTIONARIES (POINTERS);**28**;NOV 25,1997;Build 1
 ;
 ;
IT(AUTI) ; EP - INSURER TYPE - RETURNS CODE (#1) OF INSURER TYPE FILE (#9999999.181) FROM INSURER TYPE (#.211) OF INSURER FILE (#9999999.18)
 S AUTI=$G(AUTI,0) Q:'AUTI "" Q:'$G(^AUTNINS(AUTI,3)) "" Q $P($G(^AUTTINTY($G(^AUTNINS(AUTI,3)),0)),"^",2)
ITS(AUTI,AUTS) ; EP - INSURER TYPE SCREEN - RETURNS 1 OR 0 IF INSURER ENTRY (AUTI) MATCHES LIST OF INSURER TYPES (AUTS)
 Q $S("^"_$G(AUTS)_"^"[("^"_$$IT($G(AUTI))_"^"):1,1:0)
