BTPWC ;GDIT/HCSD/ALA-CREATED BY ^ATXSTX ON APR 10, 2018;
 ;;1.2;CARE MANAGEMENT EVENT TRACKING;**1**;JUL 07,2017;Build 5
 ;
 ; See referenced routines to see taxonomies being loaded.
 ;
START ;
 D ^BTPWCA ;    BTPW SIGMOID CPTS
 D ^BTPWCB ;    BTPW LEEP CPTS
 D ^BTPWCC ;    BTPW LASER CONE CPTS
 D ^BTPWCD ;    BTPW HPV DNA SCREEN CPTS
 D ^BTPWCE ;    BTPW ENDOMETRIAL BX CPTS
 D ^BTPWCF ;    BTPW CONE BX CPTS
 D ^BTPWCG ;    BTPW COLP WITH BX CPTS
 D ^BTPWCH ;    BTPW PELVIC EXAM CPTS
 D ^BTPWCI ;    BTPW PERIANAL BX CPTS
 D ^BTPWCJ ;    BTPW BRST MRI CPTS
 D ^BTPWCK ;    BTPW BRST RECON W/O IMP CPTS
 D ^BTPWCL ;    BTPW AX NODE DISECT CPTS
 D ^BTPWCM ;    BTPW MASTECTOMY UNS CPTS
 D ^BTPWCN ;    BTPW STEREO BX CPTS
 D ^BTPWCO ;    BTPW DXA CENTRAL CPTS
 D ^BTPWCP ;    BTPW NEEDLE BX GUIDED CPTS
 D ^BTPWCQ ;    BTPW NEEDLE BX CPTS
 D ^BTPWCR ;    BTPW CHLAMYDIA CPTS
 D ^BTPWCS ;    BTPW BI MASTECTOMY CPTS
 Q
