BTPWPDS1 ;GDIT/HCD/ALA-Display CMET Queued Records cont. ; 10 Apr 2017  8:06 AM
 ;;1.2;CARE MANAGEMENT EVENT TRACKING;;Jul 07, 2017;Build 71
 ;
RES(QIEN) ;EP - Calculate Result field value
 N TDATA,PRCDT,RES
 S TDATA=$G(^BTPWQ(QIEN,0))
 S PRCDT=$$FMTE^BQIUL1($P(TDATA,U,3))
 S RES=$$QLNK^BTPWPTRG(QIEN,.06)
 S:RES]"" RES=PRCDT_$C(28)_$P(RES,$C(26),2)_$C(28)_$P(RES,$C(26),3)
 Q RES
 ;
SCOMM(QIEN) ;EP - Get Status Comments
 N SIEN,SCOMM
 S SCOMM=""
 S SIEN=0
 F  S SIEN=$O(^BTPWQ(QIEN,3,SIEN)) Q:'SIEN  D
 . S SCOMM=SCOMM_$S(SCOMM]"":" ",1:"")_$G(^BTPWQ(QIEN,3,SIEN,0))
 Q SCOMM
