BGP73 ;IHS/CMI/LAB-CREATED BY ^ATXSTX ON APR 04, 2017;
 ;;17.1;IHS CLINICAL REPORTING;;MAY 10, 2017;Build 29
 ;
 ; See referenced routines to see taxonomies being loaded.
 ;
START ;
 D ^BGP73A ;    BGP FLU IZ CVX CODES
 D ^BGP73B ;    BGP CPT FLU
 D ^BGP73C ;    BGP HEPATITIS CPTS
 D ^BGP73D ;    BGP HEPATITIS CPTS
 D ^BGP73E ;    BGP HIB CPT
 D ^BGP73F ;    BGP HEDIS ANTIBIOTICS NDC
 D ^BGP73G ;    BGP HEDIS ANTIDEPRESSANT NDC
 D ^BGP73H ;    BGP HEDIS ASTHMA NDC
 D ^BGP73I ;    BGP HEDIS ASTHMA LEUK NDC
 D ^BGP73J ;    BGP HEDIS ASTHMA INHALED NDC
 D ^BGP73K ;    BGP HEDIS ACEI NDC
 D ^BGP73L ;    BGP HEDIS ARB NDC
 D ^BGP73M ;    BGP CPT MAMMOGRAM
 Q
