BGP85 ;IHS/CMI/LAB-CREATED BY ^ATXSTX ON APR 11, 2018;
 ;;18.1;IHS CLINICAL REPORTING;;MAY 25, 2018;Build 66
 ;
 ; See referenced routines to see taxonomies being loaded.
 ;
START ;
 D ^BGP85A ;    BGP IPC HIB CPT CODES
 D ^BGP85B ;    BGP IPC HIB CVX CODES
 D ^BGP85C ;    BGP IPC HEPB CPT CODES
 D ^BGP85D ;    BGP IPC HEPB CVX CODES
 D ^BGP85E ;    BGP IPC VZV CPT CODES
 D ^BGP85F ;    BGP IPC VZV CVX CODES
 D ^BGP85G ;    BGP IPC PNEUMO CPT CODES
 D ^BGP85H ;    BGP IPC PNEUMO CVX CODES
 D ^BGP85I ;    BGP IPC HEPA CVX CODES
 D ^BGP85J ;    BGP IPC HEPA CPT CODES
 D ^BGP85K ;    BGP IPC ROTA 2 DOSE CPT CODES
 D ^BGP85L ;    BGP IPC ROTA 3 DOSE CPT CODES
 D ^BGP85M ;    BGP IPC ROTA 2 DOSE CVX CODES
 D ^BGP85N ;    BGP IPC TDAP CVX CODES
 D ^BGP85O ;    BGP IPC ROTA 3 DOSE CVX CODES
 D ^BGP85P ;    BGP IPC TD CVX CODES
 D ^BGP85Q ;    BGP IPC HYSTERECTOMY CPTS
 D ^BGP85R ;    BGP IPC PAP LOINC CODES
 D ^BGP85S ;    BGP IPC HPV LOINC CODES
 D ^BGP85T ;    BGP IPC UNILAT MASTECTOMY CPTS
 D ^BGP85U ;    BGP IPC MAMMOGRAM CPTS
 D ^BGP85V ;    BGP IPC MAMMOGRAM LOINC CODES
 D ^BGP85W ;    BGP IPC TOTAL COLECTOMY CPTS
 D ^BGP85X ;    BGP IPC COLONOSCOPY CPTS
 D ^BGP85Y ;    BGP IPC FOBT LOINC CODES
 D ^BGP85Z ;    BGP IPC SIG CPT CODES
 Q
