BGP8POS2 ; IHS/CMI/LAB - NO DESCRIPTION PROVIDED 28 Jan 2005 1:34 PM ;
 ;;18.1;IHS CLINICAL REPORTING;;MAY 25, 2018;Build 66
 ;
 ;
PRE ;EP
 ;CHANGE PACKAGE FILE NAME
 S BGPX=0 F  S BGPX=$O(^BGPCTRL(BGPX)) Q:BGPX'=+BGPX  S DA=BGPX,DIK="^BGPCTRL(" D ^DIK
 S BGPX=0 F  S BGPX=$O(^BGPPEIR(BGPX)) Q:BGPX'=+BGPX  S DA=BGPX,DIK="^BGPPEIR(" D ^DIK
 S BGPX=0 F  S BGPX=$O(^BGPELIR(BGPX)) Q:BGPX'=+BGPX  S DA=BGPX,DIK="^BGPELIR(" D ^DIK
 S BGPX=0 F  S BGPX=$O(^BGPELIIR(BGPX)) Q:BGPX'=+BGPX  S DA=BGPX,DIK="^BGPELIIR(" D ^DIK
 S BGPX=0 F  S BGPX=$O(^BGPNPLR(BGPX)) Q:BGPX'=+BGPX  S DA=BGPX,DIK="^BGPNPLR(" D ^DIK
 S BGPX=0 F  S BGPX=$O(^BGPINDRC(BGPX)) Q:BGPX'=+BGPX  S DA=BGPX,DIK="^BGPINDRC(" D ^DIK
 S BGPX=0 F  S BGPX=$O(^BGPINDR(BGPX)) Q:BGPX'=+BGPX  S DA=BGPX,DIK="^BGPINDR(" D ^DIK
 S BGPX=0 F  S BGPX=$O(^BGPTAXR(BGPX)) Q:BGPX'=+BGPX  S DA=BGPX,DIK="^BGPTAXR(" D ^DIK
 S BGPX=0 F  S BGPX=$O(^BGPSNOMR(BGPX)) Q:BGPX'=+BGPX  S DA=BGPX,DIK="^BGPSNOMR(" D ^DIK
 S BGPX=0 F  S BGPX=$O(^BGPSNOSR(BGPX)) Q:BGPX'=+BGPX  S DA=BGPX,DIK="^BGPSNOSR(" D ^DIK
 Q
