BGP84 ;IHS/CMI/LAB-CREATED BY ^ATXSTX ON APR 12, 2018;
 ;;18.1;IHS CLINICAL REPORTING;;MAY 25, 2018;Build 66
 ;
 ; See referenced routines to see taxonomies being loaded.
 ;
START ;
 D ^BGP84A ;    BGP IPC OFFICE VISIT CPTS
 D ^BGP84B ;    BGP IPC PREVCARE EOV >=18 CPTS
 D ^BGP84C ;    BGP IPC PREVCARE IOV >=18 CPTS
 D ^BGP84D ;    BGP IPC HOMEHEALTH VISIT CPTS
 D ^BGP84E ;    BGP IPC ANNUAL WELLNESS CPTS
 D ^BGP84F ;    BGP IPC HBA1C LOINC CODES
 D ^BGP84G ;    BGP IPC OUTPT CONSULT CPTS
 D ^BGP84H ;    BGP IPC LT RES FACILITY CPTS
 D ^BGP84I ;    BGP IPC PREVCARE IOV 0-17 CPTS
 D ^BGP84J ;    BGP IPC PREVCARE IND COUN CPTS
 D ^BGP84K ;    BGP IPC PREVCARE GRP COUN CPTS
 D ^BGP84L ;    BGP IPC PREVCARE OTHER CPTS
 D ^BGP84M ;    BGP IPC DSCH SRV NURS FAC CPTS
 D ^BGP84N ;    BGP IPC NURS FAC VISIT CPTS
 D ^BGP84O ;    BGP IPC PERI DIALYSIS CPTS
 D ^BGP84P ;    BGP IPC HEMO DIALYSIS CPTS
 D ^BGP84Q ;    BGP IPC PREVCARE EOV 0-17 CPTS
 D ^BGP84R ;    BGP IPC FLU ENCOUNTER CPTS
 D ^BGP84S ;    BGP CPT FLU
 D ^BGP84T ;    BGP IPC INFLUENZA CPT CODES
 D ^BGP84U ;    BGP IPC DTAP CPT CODES
 D ^BGP84V ;    BGP IPC DTAP CVX CODES
 D ^BGP84W ;    BGP IPC IPV CVX CODES
 D ^BGP84X ;    BGP IPC IPV CPT CODES
 D ^BGP84Y ;    BGP IPC MMR CPT CODES
 D ^BGP84Z ;    BGP IPC MMR CVX CODES
 Q
