BGP81 ; IHS/CMI/LAB -CREATED BY ^ATXSTX ON AUG 09, 2017 ;
 ;;18.0;IHS CLINICAL REPORTING;;NOV 21, 2017;Build 51
 ;
 ; See referenced routines to see taxonomies being loaded.
 ;
START ;
 D ^BGP81A ;    BGP FLU IZ CVX CODES
 D ^BGP81B ;    BGP CPT FLU
 D ^BGP81C ;    BGP HPV CPTS
 D ^BGP81D ;    BGP PPSV23 CVX CODES
 D ^BGP81E ;    BGP PNEUMO IZ DXS
 D ^BGP81F ;    BGP PPSV23 CPT CODES
 D ^BGP81G ;    BGP PCV13 CVX CODES
 D ^BGP81H ;    BGP HIB CPT
 D ^BGP81I ;    BGP MENINGOCOCCAL CVX CODES
 D ^BGP81J ;    BGP CPT MENINGOCOCCAL
 D ^BGP81K ;    BGP MENINGOCOCCAL CVX CODES
 D ^BGP81L ;    BGP HPV CVX CODES
 D ^BGP81M ;    BGP SIG CPTS
 D ^BGP81N ;    BGP COLO CPTS
 D ^BGP81O ;    BGP CPT HIV TESTS
 D ^BGP81P ;    BGP CT COLONOGRAPHY CPTS
 D ^BGP81Q ;    BGP FIT-DNA CPTS
 D ^BGP81R ;    BGP CPT PREGNANCY TEST
 D ^BGP81S ;    BGP CPT XRAY
 D ^BGP81T ;    BGP CHLAMYDIA LOINC CODES
 D ^BGP81U ;    BGP FIT-DNA LOINC CODES
 D ^BGP81V ;    BGP ASTHMA LABA NDC
 D ^BGP81W ;    BGP HEDIS ANTICHOLINERGIC NDC
 D ^BGP81X ;    BGP HEDIS ANTITHROMBOTIC NDC
 D ^BGP81Y ;    BGP HEDIS ANTI-INFECTIVE NDC
 D ^BGP81Z ;    BGP HEDIS CARDIOVASCULAR NDC
 Q
