BGP83 ; IHS/CMI/LAB -CREATED BY ^ATXSTX ON SEP 11, 2017 ;
 ;;18.0;IHS CLINICAL REPORTING;;NOV 21, 2017;Build 51
 ;
 ; See referenced routines to see taxonomies being loaded.
 ;
START ;
 D ^BGP83A ;    BGP PQA BENZODIAZ OP NDC
 D ^BGP83B ;    BGP DENTAL VISIT CPT CODES
 D ^BGP83C ;    BGP DENTAL VISIT DXS
 D ^BGP83D ;    BGP DENTAL EXAM CPTS
 D ^BGP83E ;    BGP CPT SEXUAL ACTIVITY
 D ^BGP83F ;    BGP EMPHYSEMA DXS
 D ^BGP83G ;    BGP HEART FAILURE DXS
 D ^BGP83H ;    BGP PAP SMEAR DXS
 D ^BGP83I ;    BGP CPT PAP
 D ^BGP83J ;    BGP ESRD CPTS
 D ^BGP83K ;    BGP HIV VIRAL LOAD CPTS
 D ^BGP83L ;    BGP DENTAL EXAM DXS
 Q
