BGP82 ; IHS/CMI/LAB -CREATED BY ^ATXSTX ON AUG 09, 2017 ;
 ;;18.0;IHS CLINICAL REPORTING;;NOV 21, 2017;Build 51
 ;
 ; See referenced routines to see taxonomies being loaded.
 ;
START ;
 D ^BGP82A ;    BGP HEDIS CENTRAL NERVOUS NDC
 D ^BGP82B ;    BGP HEDIS CONTRACEPTION NDC
 D ^BGP82C ;    BGP HEDIS NONBENZODIAZ NDC
 D ^BGP82D ;    BGP HEDIS ENDOCRINE NDC
 D ^BGP82E ;    BGP HEDIS ISOTRETINOIN NDC
 D ^BGP82F ;    BGP HEDIS PAIN NDC
 D ^BGP82G ;    BGP HEDIS SKL MUSCLE RELAX NDC
 D ^BGP82H ;    BGP PQA BETA BLOCKER NDC
 D ^BGP82I ;    BGP PQA RASA NDC
 D ^BGP82J ;    BGP PQA CCB NDC
 D ^BGP82K ;    BGP PQA BIGUANIDE NDC
 D ^BGP82L ;    BGP PQA SULFONYLUREA NDC
 D ^BGP82M ;    BGP PQA THIAZOLIDINEDIONE NDC
 D ^BGP82N ;    BGP PQA DPP IV NDC
 D ^BGP82O ;    BGP PQA DIABETES ALL CLASS NDC
 D ^BGP82P ;    BGP PQA STATIN NDC
 D ^BGP82Q ;    BGP PQA ANTIRETROVIRAL NDC
 D ^BGP82R ;    BGP PQA SABA NDC
 D ^BGP82S ;    BGP PQA CONTROLLER NDC
 D ^BGP82T ;    BGP PQA NON-WARF ANTICOAG NDC
 D ^BGP82U ;    BGP PQA WARFARIN NDC
 D ^BGP82V ;    BGP PQA ASTHMA INHALE STER NDC
 D ^BGP82W ;    BGP PQA COPD NDC
 D ^BGP82X ;    BGP PQA BENZODIAZ NDC
 D ^BGP82Y ;    BGP PQA ARB NEPRILYSIN NDC
 D ^BGP82Z ;    BGP PQA OPIOID NDC
 Q
