BGP8ASL1 ;IHS/CMI/LAB - DISPLAY IND LISTS;
 ;;18.1;IHS CLINICAL REPORTING;**1**;MAY 25, 2018;Build 65
 ;; ;
NGR ;EP
 K BGPTIND S BGPHIGH=""
 S BGPSUCNT=0,BGPSU="",BGPSUC=0
 S BGPX=0 F  S BGPX=$O(^BGPGPDCR(BGPX)) Q:BGPX'=+BGPX  S V=$G(^BGPGPDCR(BGPX,0)) D
 .Q:'$D(^BGPGPDCR(BGPX,0))
 .Q:$P(V,U)'=BGPBD
 .Q:$P(V,U,2)'=BGPED
 .Q:$P(V,U,7)'=BGPPER
 .Q:$P(V,U,21)'=$$VER^BGP8BAN()
 .I $G(BGPYGPU),$P(V,U,12)'=9 Q
 .I '$G(BGPYGPU),$P(V,U,12)'=1 Q
 .Q:$P(V,U,20)  ;DPRV
 .;I $G(BGPCHWE) Q:'$O(^BGPGPDCR(BGPX,88888,0))
 .Q:$P(V,U,5)'=BGPBBD
 .Q:$P(V,U,6)'=BGPBED
 .Q:$P(V,U,14)'=BGPBEN
 .S BGPSUC=BGPSUC+1,BGPTIND(BGPSUC,0)=BGPSUC_")"
 .S Y=""
 .S $E(Y,4)=$E($$SU($P(V,U,11)),1,10)
 .S $E(Y,15)=$E($$FAC($P(V,U,9)),1,13)_$S($P(^BGPGPDCR(BGPX,0),U,17):"+",1:"")
 .S $E(Y,30)=$$DATE^BGP8UTL($P(V,U))
 .S $E(Y,40)=$$DATE^BGP8UTL($P(V,U,2))
 .S $E(Y,50)=$$DATE^BGP8UTL($P(V,U,5))
 .S $E(Y,60)=$$DATE^BGP8UTL($P(V,U,6))
 .S $E(Y,70)=$$DATE^BGP8UTL($P(V,U,13))
 .S BGPTIND(BGPSUC,0)=BGPTIND(BGPSUC,0)_Y
 .S BGPTIND(BGPSUC,BGPSUC)=BGPX
 .I $D(BGPSUL(BGPX)) S BGPTIND(BGPSUC,0)="*"_BGPTIND(BGPSUC,0)
 .Q
 S (VALMCNT,BGPHIGH)=BGPSUC
 Q
 ;
ONM ;EP
 K BGPTIND S BGPHIGH=""
 S BGPSUCNT=0,BGPSU="",BGPSUC=0
 S BGPX=0 F  S BGPX=$O(^BGPGPDCR(BGPX)) Q:BGPX'=+BGPX  S V=$G(^BGPGPDCR(BGPX,0)) D
 .Q:'$D(^BGPGPDCR(BGPX,0))
 .Q:$P(V,U)'=BGPBD
 .Q:$P(V,U,2)'=BGPED
 .Q:$P(V,U,7)'=BGPPER
 .Q:$P(V,U,21)'=$$VER^BGP8BAN()
 .Q:$P(V,U,5)'=BGPBBD
 .Q:$P(V,U,6)'=BGPBED
 .Q:$P(V,U,14)'=BGPBEN
 .Q:$P(V,U,12)'=7
 .S BGPSUC=BGPSUC+1,BGPTIND(BGPSUC,0)=BGPSUC_")"
 .S Y=""
 .S $E(Y,4)=$E($$SU($P(V,U,11)),1,10)
 .S $E(Y,15)=$E($$FAC($P(V,U,9)),1,13)_$S($P(^BGPGPDCR(BGPX,0),U,17):"+",1:"")
 .S $E(Y,30)=$$DATE^BGP8UTL($P(V,U))
 .S $E(Y,40)=$$DATE^BGP8UTL($P(V,U,2))
 .S $E(Y,50)=$$DATE^BGP8UTL($P(V,U,5))
 .S $E(Y,60)=$$DATE^BGP8UTL($P(V,U,6))
 .S $E(Y,70)=$$DATE^BGP8UTL($P(V,U,13))
 .S BGPTIND(BGPSUC,0)=BGPTIND(BGPSUC,0)_Y
 .S BGPTIND(BGPSUC,BGPSUC)=BGPX
 .I $D(BGPSUL(BGPX)) S BGPTIND(BGPSUC,0)="*"_BGPTIND(BGPSUC,0)
 .Q
 S (VALMCNT,BGPHIGH)=BGPSUC
 Q
 ;
ELD ;EP
 K BGPTIND S BGPHIGH=""
 S BGPSUCNT=0,BGPSU="",BGPSUC=0
 S BGPX=0 F  S BGPX=$O(^BGPEDLCR(BGPX)) Q:BGPX'=+BGPX  I BGPX S V=$G(^BGPEDLCR(BGPX,0)) D
 .Q:'$D(^BGPEDLCR(BGPX,0))
 .Q:$P(V,U)'=BGPBD
 .Q:$P(V,U,2)'=BGPED
 .Q:$P(V,U,7)'=BGPPER
 .Q:$P(V,U,12)'=5
 .Q:$P(V,U,5)'=BGPBBD
 .Q:$P(V,U,6)'=BGPBED
 .Q:$P(V,U,14)'=BGPBEN
 .S BGPSUC=BGPSUC+1,BGPTIND(BGPSUC,0)=BGPSUC_")"
 .S Y=""
 .S $E(Y,4)=$E($$SU($P(V,U,11)),1,10)
 .S $E(Y,15)=$E($$FAC($P(V,U,9)),1,13)_$S($P(^BGPEDLCR(BGPX,0),U,17):"+",1:"")
 .S $E(Y,30)=$$DATE^BGP8UTL($P(V,U))
 .S $E(Y,40)=$$DATE^BGP8UTL($P(V,U,2))
 .S $E(Y,50)=$$DATE^BGP8UTL($P(V,U,5))
 .S $E(Y,60)=$$DATE^BGP8UTL($P(V,U,6))
 .S $E(Y,70)=$$DATE^BGP8UTL($P(V,U,13))
 .S BGPTIND(BGPSUC,0)=BGPTIND(BGPSUC,0)_Y
 .S BGPTIND(BGPSUC,BGPSUC)=BGPX
 .I $D(BGPSUL(BGPX)) S BGPTIND(BGPSUC,0)="*"_BGPTIND(BGPSUC,0)
 .Q
 S (VALMCNT,BGPHIGH)=BGPSUC
 Q
PED ;EP
 K BGPTIND S BGPHIGH=""
 S BGPSUCNT=0,BGPSU="",BGPSUC=0
 S BGPX=0 F  S BGPX=$O(^BGPPEDCR(BGPX)) Q:BGPX'=+BGPX  I BGPX S V=$G(^BGPPEDCR(BGPX,0)) D
 .Q:'$D(^BGPPEDCR(BGPX,0))
 .Q:$P(V,U)'=BGPBD
 .Q:$P(V,U,2)'=BGPED
 .Q:$P(V,U,7)'=BGPPER
 .Q:$P(V,U,5)'=BGPBBD
 .Q:$P(V,U,6)'=BGPBED
 .Q:$P(V,U,11)'=BGPBEN
 .Q:$P(V,U,20)  ;MEGAN
 .S BGPSUC=BGPSUC+1,BGPTIND(BGPSUC,0)=BGPSUC_")"
 .S Y=""
 .S $E(Y,4)=$E($$SU($P(V,U,10)),1,10)
 .S $E(Y,15)=$E($$FAC($P(V,U,9)),1,13)_$S($P(^BGPPEDCR(BGPX,0),U,17):"+",1:"")
 .S $E(Y,30)=$$DATE^BGP8UTL($P(V,U))
 .S $E(Y,40)=$$DATE^BGP8UTL($P(V,U,2))
 .S $E(Y,50)=$$DATE^BGP8UTL($P(V,U,5))
 .S $E(Y,60)=$$DATE^BGP8UTL($P(V,U,6))
 .S $E(Y,70)=$$DATE^BGP8UTL($P(V,U,13))
 .S BGPTIND(BGPSUC,0)=BGPTIND(BGPSUC,0)_Y
 .S BGPTIND(BGPSUC,BGPSUC)=BGPX
 .I $D(BGPSUL(BGPX)) S BGPTIND(BGPSUC,0)="*"_BGPTIND(BGPSUC,0)
 .Q
 S (VALMCNT,BGPHIGH)=BGPSUC
 Q
FAC(S) ;
 NEW N S N=$O(^AUTTLOC("C",S,0))
 I N="" Q N
 Q $P(^DIC(4,N,0),U)
SU(S) ;
 NEW N S N=$O(^AUTTSU("C",S,0))
 I N="" Q N
 Q $P(^AUTTSU(N,0),U)
