BGP86 ;IHS/CMI/LAB-CREATED BY ^ATXSTX ON APR 30, 2018;
 ;;18.1;IHS CLINICAL REPORTING;;MAY 25, 2018;Build 66
 ;
 ; See referenced routines to see taxonomies being loaded.
 ;
START ;
 D ^BGP86A ;    BGP IPC FIT-DNA LOINC CODES
 D ^BGP86B ;    BGP IPC CT COLONOGRAPHY CPTS
 D ^BGP86C ;    BGP IPC DEP SCRN ENC CPTS
 D ^BGP86D ;    BGP IPC LONG TERM CARE CPTS
 D ^BGP86E ;    BGP IPC PSYCH VISIT CPTS
 D ^BGP86F ;    BGP IPC BMI ENCOUNTER CPTS
 D ^BGP86G ;    BGP IPC ADA BMI CPTS
 D ^BGP86H ;    BGP IPC ABOVE NORMAL FU DXS
 D ^BGP86I ;    BGP IPC ABOVE NORMAL FU CPTS
 D ^BGP86J ;    BGP IPC BELOW NORMAL FU CPTS
 D ^BGP86K ;    BGP IPC BELOW NORMAL FU DXS
 D ^BGP86L ;    BGP IPC NUTR COUN CPTS
 D ^BGP86M ;    BGP IPC VASCULAR ACC DIAL CPTS
 D ^BGP86N ;    BGP IPC ESRD OPT SRV CPTS
 D ^BGP86O ;    BGP IPC KIDNEY TRANSPLANT CPTS
 D ^BGP86P ;    BGP IPC DIALYSIS SRV CPTS
 D ^BGP86Q ;    BGP IPC ADULT OPT CPTS
 D ^BGP86R ;    BGP IPC INFLUENZA CVX CODES
 Q
