BGP8Y ;IHS/CMI/LAB-CREATED BY ^ATXSTX ON FEB 08, 2018;
 ;;18.0;IHS CLINICAL REPORTING;**1**;NOV 21, 2017;Build 62
 ;
 ; See referenced routines to see taxonomies being loaded.
 ;
START ;
 D ^BGP8YA ;    BGP PQA NEBULIZED BRONCHO NDC
 D ^BGP8YB ;    BGP PQA NON-INFUSED MS NDC
 D ^BGP8YC ;    BGP PQA INFUSED MS NDC
 D ^BGP8YD ;    BGP CPT FOOT AMP UNKNOWN SIDE
 D ^BGP8YE ;    BGP GROUP A STREP LOINC
 D ^BGP8YF ;    BGP HPV LOINC CODES
 Q
