BGP8Z ;IHS/CMI/LAB-CREATED BY ^ATXSTX ON FEB 13, 2018;
 ;;18.0;IHS CLINICAL REPORTING;**1**;NOV 21, 2017;Build 62
 ;
 ; See referenced routines to see taxonomies being loaded.
 ;
START ;
 D ^BGP8ZA ;    BGP DM RETINAL EXAM CPTS
 D ^BGP8ZB ;    BGP EYE ENUCLEATION CPTS
 D ^BGP8ZC ;    BGP CPT FLU
 D ^BGP8ZD ;    BGP ZOSTER SHINGRIX CPTS
 D ^BGP8ZE ;    BGP CPT HOSPICE
 D ^BGP8ZF ;    BGP DENTAL EXAM CPTS
 D ^BGP8ZG ;    BGP CT COLONOGRAPHY CPTS
 D ^BGP8ZH ;    BGP HEDIS ANTIBIOTICS NDC
 D ^BGP8ZI ;    BGP HEDIS ANTIDEPRESSANT NDC
 D ^BGP8ZJ ;    BGP HEDIS ASTHMA NDC
 D ^BGP8ZK ;    BGP HEDIS ASTHMA LEUK NDC
 D ^BGP8ZL ;    BGP HEDIS ASTHMA INHALED NDC
 D ^BGP8ZM ;    BGP HEDIS CONTRACEPTION NDC
 D ^BGP8ZN ;    BGP HEDIS ISOTRETINOIN NDC
 D ^BGP8ZO ;    BGP HEDIS ANTITHROMBOTIC NDC
 D ^BGP8ZP ;    BGP HEDIS ANTICHOLINERGIC NDC
 D ^BGP8ZQ ;    BGP HEDIS ANTI-INFECTIVE NDC
 D ^BGP8ZR ;    BGP HEDIS CARDIOVASCULAR NDC
 D ^BGP8ZS ;    BGP HEDIS CENTRAL NERVOUS NDC
 D ^BGP8ZT ;    BGP HEDIS NONBENZODIAZ NDC
 D ^BGP8ZU ;    BGP HEDIS ENDOCRINE NDC
 D ^BGP8ZV ;    BGP HEDIS PAIN NDC
 D ^BGP8ZW ;    BGP HEDIS SKL MUSCLE RELAX NDC
 D ^BGP8ZX ;    BGP HEDIS ACEI NDC
 D ^BGP8ZY ;    BGP HEDIS ARB NDC
 D ^BGP8ZZ ;    BGP PQA LA INHALED BRONCHO NDC
 Q
