BGP8PARP ; IHS/CMI/LAB - IHS gpra print ;
 ;;18.1;IHS CLINICAL REPORTING;;MAY 25, 2018;Build 66
 ;
 ;
PRINT ;EP
 I $G(BGPDASH) D AREA^BGP8DBPR Q
 K ^TMP($J)
 S BGPIOSL=$S($G(BGPGUI):55,1:IOSL)
 S BGPGPG=0
 S BGPQUIT=""
 S BGPIFTR=""
 S ^TMP($J,"BGPDEL",0)=0
 S BGPPTYPE="P"
 D SETEXCEL^BGP8DP
 I BGPROT="D" G DEL
 D AREACP^BGP8DH
 S BGPQUIT="",BGPGPG=0,BGPRPT=0
 D PRINT1^BGP8DP
 Q:BGPQUIT
 S BGPIFTR=1
 Q:BGPROT="P"
DEL ;create delimited output file
 S BGPQUIT="",BGPGPG=0,BGPRPT=0,BGPIFTR=""
 D ^%ZISC ;close printer device
 K ^TMP($J)
 ;D ^BGP8PDL ;create ^tmp of delimited report
 S ^TMP($J,"BGPDEL",0)=0
 S BGPPTYPE="D",BGPQUIT=0
 D AREACP^BGP8DH
 S BGPQUIT="",BGPGPG=0,BGPRPT=0
 D PRINT1^BGP8DP
 I '$G(BGPNODEL) D SAVEDEL^BGP8PDL   ;D ^BGP8PDL ;create ^tmp of delimited report
 S BGPIFTR=1
 K ^TMP($J)
 Q
 ;
