AGMBIR1 ;IHS/OIT/NKD - PAT REG MBI DETAIL ; JULY 23, 2018
 ;;7.1;PATIENT REGISTRATION;**14**;AUG 25, 2005;Build 1
 ;
 ;IHS/OIT/NKD AG*7.1*14 MBI PHASE 2
 ;
PAT  ; PATIENT LOOKUP
 N DFN,RHIFLAG,REC,AGPATDFN,AGRES
 D PTLK^AG
 Q:'$D(DFN)!$D(DUOUT)!$D(DFOUT)!$D(DTOUT)!$D(DIRUT)
PRINT  ; PRINT DETAILS
 S AGRES=$$GETMBIS^AGUTL(DFN,"AGRES")
 I 'AGRES W !!,"Patient has no MBI history on file."
 E  D
 . W !!,?10,"Eff Date",?26,"MBI",?40,"Source"
 . N CNT S CNT=0 F  S CNT=$O(AGRES(CNT)) Q:'CNT  D
 . . W !,$$RJ^XLFSTR(CNT_")",6),?10,$P(AGRES(CNT,0),U,2),?26,$P(AGRES(CNT,0),U,3),?40,$P(AGRES(CNT,0),U,4)
END  ; CLEANUP
 K DIR
 S DIR("A")="Press RETURN..."
 S DIR(0)="E"
 D ^DIR
 K DIR
 D ^XBFMK,KILL^AUPNPAT
 Q
