BQIBTX ;GDHD/HCS/ALA-CREATED BY ^ATXSTX ON FEB 13, 2017;
 ;;2.6;ICARE MANAGEMENT SYSTEM;;Jul 07, 2017;Build 72
 ;
 ; See referenced routines to see taxonomies being loaded.
 ;
START ;
 D ^BQIBTXA ;   BQI TB QUANTIFERON LOINC
 D ^BQIBTXB ;   BQI PROSTATE SCRN CPTS
 D ^BQIBTXC ;   BQI PSA LOINC CODES
 D ^BQIBTXD ;   BQI PROSTATE BIOPSY CPTS
 D ^BQIBTXE ;   BQI PROSTATE ULTRASOUND CPTS
 D ^BQIBTXF ;   BTPW MAMMOGRAM BI DX CPTS
 D ^BQIBTXG ;   BTPW MAMMOGRAM SCREEN CPTS
 D ^BQIBTXH ;   BTPW MAMMOGRAM UNI DX CPTS
 Q
