BQIRGDMT ;GDHD/HCS/ALA-Test DM Audit ; 15 Dec 2016  2:57 PM
 ;;2.6;ICARE MANAGEMENT SYSTEM;;Jul 07, 2017;Build 72
 ;;
 ;
EN ;EP
 ;Select Patient
 S DIC="^AUPNPAT(",DIC(0)="AEMQ" D ^DIC K DIC
 Q:Y<0
 I $D(APCDPARM),$P(APCDPARM,U,3)="Y" W !?25,"Ok" S %=1 D YN^DICN Q:%'=1
 S APCDPAT=+Y
 D INAC^APCDEA(APCDPAT,.X) I 'X S APCDPAT="" Q
 ;
 S DIC(0)="AEMNZ",DIC="^BDMDMTX(" D ^DIC
 S DA=+Y I DA=-1 Q
 S BDMN=0
 F  S BDMN=$O(^BDMDMTX(DA,11,BDMN)) Q:'BDMN  D
 . S BDMDATA=$G(^BDMDMTX(DA,11,BDMN,1)) I BDMDATA="" Q
 . I $P(BDMDATA,U,4)="" Q
 . S DFN=AUPNPAT
 . S EVAL=$P(BDMDATA,U,3) I EVAL'["~" Q
 . S EVAL=$TR(EVAL,"~","^")
 . W !,$P(BDMDATA,U,1),"|",$$AUD^BQIRGDMA(EVAL)
