BDMDGZ ;IHS/CMI/LAB-CREATED BY ^ATXSTX ON NOV 05, 2018;
 ;;2.0;DIABETES MANAGEMENT SYSTEM;**12**;JUN 14, 2007;Build 51
 ;
 ; See referenced routines to see taxonomies being loaded.
 ;
START ;
 D ^BDMDGZA ;   BGP DM ATK AMP CPTS
 D ^BDMDGZB ;   BGP DM ATK AMP DXS
 D ^BDMDGZC ;   BGP DM BTK AMP CPTS
 D ^BDMDGZD ;   BGP DM BTK AMP CTS
 D ^BDMDGZE ;   BGP DM BTK AMP DXS
 D ^BDMDGZF ;   BGP DM BTK AMP PROCS
 Q
