BDMDFX ;IHS/CMI/LAB-CREATED BY ^ATXSTX ON OCT 31, 2017;
 ;;2.0;DIABETES MANAGEMENT SYSTEM;**11**;JUN 14, 2007;Build 30
 ;
 ; See referenced routines to see taxonomies being loaded.
 ;
START ;
 D ^BDMDFXA ;   DM AUDIT EYE EXAM CPTS
 D ^BDMDFXB ;   DM AUDIT EYE EXAM PROCS
 D ^BDMDFXC ;   DM AUDIT TYPE I DXS
 D ^BDMDFXD ;   DM AUDIT TYPE II DXS
 Q
