BUDD1 ; IHS/CMI/LAB -CREATED BY ^ATXSTX ON NOV 30, 2016 ;
 ;;11.0;IHS/RPMS UNIFORM DATA SYSTEM;;JAN 18, 2017;Build 66
 ;
 ; See referenced routines to see taxonomies being loaded.
 ;
START ;
 D ^BUDD1A ;    BUD HYSTERECTOMY CPTS UDS16
 D ^BUDD1B ;    BUD PAP CPTS UDS 16
 D ^BUDD1C ;    BUD HIV DXS
 D ^BUDD1D ;    BUD DIABETES MEDS NDC
 Q
