BUDE2 ; IHS/CMI/LAB -CREATED BY ^ATXSTX ON OCT 17, 2017 ;
 ;;12.0;IHS/RPMS UNIFORM DATA SYSTEM;;NOV 22, 2017;Build 75
 ;
 ; See referenced routines to see taxonomies being loaded.
 ;
START ;
 D ^BUDE2A ;    BUD 17 T6A LINE 22
 D ^BUDE2B ;    BUD 17 T6A LINE 23
 D ^BUDE2C ;    BUD 17 T6A LINE 25
 D ^BUDE2D ;    BUD HPV CPTS
 D ^BUDE2E ;    BUD HPV LOINC CODES
 D ^BUDE2F ;    BUD PAP SMEAR DXS 17
 D ^BUDE2G ;    BUD CPT PAP UDS 17
 D ^BUDE2H ;    BUD PAP SMEAR DXS 17
 Q
