ATXFD ;IHS/CMI/LAB-CREATED BY ^ATXSTX ON JAN 02, 2018;
 ;;5.1;TAXONOMY;**25**;FEB 04, 1997;Build 47
 ;
 ; See referenced routines to see taxonomies being loaded.
 ;
START ;
 D ^ATXFDA ;    BGP CHD DXS
 D ^ATXFDB ;    BGP IVD DXS
 D ^ATXFDC ;    BGP SEXUAL ACTIVITY DXS
 D ^ATXFDD ;    BGP LEFT EYE ENUCLEATION PROCS
 D ^ATXFDE ;    BGP RIGHT EYE ENUCLEATION PROC
 D ^ATXFDF ;    BGP DM MACULAR EDEMA DX
 D ^ATXFDG ;    BGP DM RETINOPATHY DX
 D ^ATXFDH ;    BGP LOWER EXT AMP ANY CPT
 D ^ATXFDI ;    BGP LOWER EXT AMP ANY DX
 D ^ATXFDJ ;    BGP LOWER EXT AMP ANY PROC ICD
 Q
