ATXF6 ;IHS/CMI/LAB-CREATED BY ^ATXSTX ON JAN 02, 2017;
 ;;5.1;TAXONOMY;**19**;FEB 04, 1997;Build 32
 ;
 ; See referenced routines to see taxonomies being loaded.
 ;
START ;
 D ^ATXF6A ;    BGP ESRD PMS DXS
 D ^ATXF6B ;    BGP PREGNANCY TRI 1 DXS
 D ^ATXF6C ;    BGP PREGNANCY TRI 2 DXS
 D ^ATXF6D ;    BGP PREGNANCY TRI 3 DXS
 D ^ATXF6E ;    BGP TOPICAL FLUORIDE DXS
 D ^ATXF6F ;    BQI CKD NOS DXS
 D ^ATXF6G ;    BQI CKD STG 1 DXS
 D ^ATXF6H ;    BQI CKD STG 2 DXS
 D ^ATXF6I ;    BQI CKD STG 3 DXS
 D ^ATXF6J ;    BQI CKD STG 4 DXS
 D ^ATXF6K ;    BQI CKD STG 5 DXS
 D ^ATXF6L ;    BQI ESRD DXS
 D ^ATXF6M ;    BQI GLAUCOMA DXS
 D ^ATXF6N ;    BQI PROSTATE SCREEN DXS
 D ^ATXF6O ;    BGP PREGNANCY DIAGNOSES 2
 Q
