ATXFE ;IHS/CMI/LAB-CREATED BY ^ATXSTX ON OCT 22, 2018;
 ;;5.1;TAXONOMY;**26**;FEB 04, 1997;Build 48
 ;
 ; See referenced routines to see taxonomies being loaded.
 ;
START ;
 D ^ATXFEA ;    BGP DM ATK AMP DXS
 D ^ATXFEB ;    BGP DM ATK AMP PROCS
 D ^ATXFEC ;    BGP DM BTK AMP DXS
 D ^ATXFED ;    BGP DM BTK AMP PROCS
 D ^ATXFEE ;    BGP FLU IZ DXS
 D ^ATXFEF ;    BGP SEXUAL ACTIVITY DXS
 D ^ATXFEG ;    BGP SUICIDAL IDEATION DXS
 Q
