ATXF0 ;IHS/CMI/LAB-CREATED BY ^ATXSTX ON JUN 29, 2017;
 ;;5.1;TAXONOMY;**23**;FEB 04, 1997;Build 39
 ;
 ; See referenced routines to see taxonomies being loaded.
 ;
START ;
 D ^ATXF0A ;    BGP BIPOLAR DEPRESSION DXS
 D ^ATXF0B ;    BGP COLORECTAL CANCER DXS
 D ^ATXF0C ;    BGP COPD DXS
 D ^ATXF0D ;    BGP DENTAL EXAM DXS
 D ^ATXF0E ;    BGP ENCEPHALOPATHY DXS
 D ^ATXF0F ;    BGP HYSTERECTOMY PROCEDURES
 D ^ATXF0G ;    BGP IMMUNODEFICIENCY DXS
 D ^ATXF0H ;    BGP INTUSSUSCEPTION DXS
 D ^ATXF0I ;    BGP LYMPHO CANCER DXS
 D ^ATXF0J ;    BGP MOOD DISORDERS
 D ^ATXF0K ;    BGP OPEN ANGLE GLAUCOMA DXS
 D ^ATXF0L ;    BGP PQA CANCER DXS
 D ^ATXF0M ;    BGP PREGNANCY DIAGNOSES 2
 D ^ATXF0N ;    BGP SCID DXS
 D ^ATXF0O ;    BGP SEXUAL ACTIVITY DXS
 D ^ATXF0P ;    BGP SEXUAL ACTIVITY PROCEDURES
 D ^ATXF0Q ;    BGP TIA DXS
 D ^ATXF0R ;    BGP URI DXS
 D ^ATXF0S ;    BGP VACCINE ADVERSE EFFECT
 D ^ATXF0T ;    SURVEILLANCE DIABETES
 Q
