ATXFB ;IHS/CMI/LAB-CREATED BY ^ATXSTX ON JAN 23, 2018;
 ;;5.1;TAXONOMY;**25**;FEB 04, 1997;Build 47
 ;
 ; See referenced routines to see taxonomies being loaded.
 ;
START ;
 D ^ATXFBA ;    BGP AMI DXS PAMT
 D ^ATXFBB ;    BGP ARTERIAL DISEASE DXS
 D ^ATXFBC ;    BGP BILATERAL BLINDNESS DXS
 D ^ATXFBD ;    BGP BREASTFEEDING DXS
 D ^ATXFBE ;    BGP CAROTID INTERVENTION PROCS
 D ^ATXFBF ;    BGP COPD DXS
 D ^ATXFBG ;    BGP EXERCISE COUNSELING DXS
 D ^ATXFBH ;    BGP EYE EXAM PROCS
 D ^ATXFBI ;    BGP HYPERCHOLESTEROLEMIA DXS
 D ^ATXFBJ ;    BGP IPC ABOVE NORMAL FU DXS
 D ^ATXFBK ;    BGP IPC BILAT MASTECTOMY DXS
 D ^ATXFBL ;    BGP IPC BIPOLAR DIAG DXS
 D ^ATXFBM ;    BGP IPC BIPOLAR DISORDER DXS
 D ^ATXFBN ;    BGP IPC CKD STG 5 DXS
 D ^ATXFBO ;    BGP IPC COLON CANCER DXS
 D ^ATXFBP ;    BGP IPC DEPRESSION DIAG DXS
 D ^ATXFBQ ;    BGP IPC DIABETES DXS
 D ^ATXFBR ;    BGP IPC DYSTHYMIA DXS
 D ^ATXFBS ;    BGP IPC EGG ALLERGY DXS
 D ^ATXFBT ;    BGP IPC ESRD DXS
 D ^ATXFBU ;    BGP IPC ESSENTIAL HTN DXS
 D ^ATXFBV ;    BGP IPC HEP A DXS
 D ^ATXFBW ;    BGP IPC HEP B DXS
 D ^ATXFBX ;    BGP IPC HIV DXS
 D ^ATXFBY ;    BGP IPC IMMUNE DISORDERS DXS
 Q
