ATXF7 ;IHS/CMI/LAB-CREATED BY ^ATXSTX ON JAN 31, 2017;
 ;;5.1;TAXONOMY;**20**;FEB 04, 1997;Build 33
 ;
 ; See referenced routines to see taxonomies being loaded.
 ;
START ;
 D ^ATXF7A ;    BI HIGH RISK HEPA/B, CLD/HEPC
 D ^ATXF7B ;    DM AUDIT DEPRESSIVE DISORDERS
 D ^ATXF7C ;    DM AUDIT REFRACTION DXS
 D ^ATXF7D ;    DM AUDIT TYPE I DXS
 D ^ATXF7E ;    DM AUDIT TYPE II DXS
 D ^ATXF7F ;    SURVEILLANCE DIABETES
 D ^ATXF7G ;    BQI GEST DM DXS
 D ^ATXF7H ;    BQI ADD/ADHD DXS
 Q
