ATXFA ;IHS/CMI/LAB-CREATED BY ^ATXSTX ON NOV 01, 2017;
 ;;5.1;TAXONOMY;**24**;FEB 04, 1997;Build 40
 ;
 ; See referenced routines to see taxonomies being loaded.
 ;
START ;
 D ^ATXFAA ;    BQI CANCER REPORTABLE DXS
 D ^ATXFAB ;    BQI CANCER SUPPLEMENTAL DXS
 D ^ATXFAC ;    BQI EXERCISE COUNSELING DXS
 D ^ATXFAD ;    BQI SUICIDE ATTEMPT DXS
 D ^ATXFAE ;    DM AUDIT DIABETIC RETINOPATHY
 Q
