ATXFC ;IHS/CMI/LAB-CREATED BY ^ATXSTX ON JAN 11, 2018;
 ;;5.1;TAXONOMY;**25**;FEB 04, 1997;Build 47
 ;
 ; See referenced routines to see taxonomies being loaded.
 ;
START ;
 D ^ATXFCA ;    BGP IPC INTUSSUSCEPTIONS DXS
 D ^ATXFCB ;    BGP IPC IZ ENCEPHALOPATHY DXS
 D ^ATXFCC ;    BGP IPC LT MASTECTOMY DXS
 D ^ATXFCD ;    BGP IPC LYMPHATIC CANCER DXS
 D ^ATXFCE ;    BGP IPC MAJOR DEPRESSION DXS
 D ^ATXFCF ;    BGP IPC MEASLES DXS
 D ^ATXFCG ;    BGP IPC MUMPS DXS
 D ^ATXFCH ;    BGP IPC PALLIATIVE CARE DXS
 D ^ATXFCI ;    BGP IPC PERSONALITY DIS DXS
 D ^ATXFCJ ;    BGP IPC PREGNANCY CMS69 DXS
 D ^ATXFCK ;    BGP IPC PREGNANCY DXS
 D ^ATXFCL ;    BGP IPC RT MASTECTOMY DXS
 D ^ATXFCM ;    BGP IPC RUBELLA DXS
 D ^ATXFCN ;    BGP IPC SCID DXS
 D ^ATXFCO ;    BGP IPC UNILAT MASTECTOMY DXS
 D ^ATXFCP ;    BGP IPC VARICELLA DXS
 D ^ATXFCQ ;    BGP LIVER DISEASE DXS
 D ^ATXFCR ;    BGP PREGNANCY DIAGNOSES 2
 D ^ATXFCS ;    BGP RHABDOMYOLYSIS DX
 D ^ATXFCT ;    BGP TIA DXS
 D ^ATXFCU ;    BGP FOOT AMP PROCEDURES
 D ^ATXFCV ;    BGP LEFT FOOT AMP PROCS
 D ^ATXFCW ;    BGP LEFT FOOT AMP DXS
 D ^ATXFCX ;    BGP RIGHT FOOT AMP DXS
 D ^ATXFCY ;    BGP RIGHT FOOT AMP PROCS
 D ^ATXFCZ ;    BGP UNILATERAL FOOT AMP DXS
 Q
