ADE6P311 ;IHS/OIT/GAB - ADE6.0 PATCH 31 [ 09/09/16  8:37 AM ]
 ;;6.0;ADE*6.0*31;;March 25, 1999;Build 28
 ;IHS/OIT/GAB 9/2016 Patch 31 ADA-CDT code updates for 2017
 ;IHS/OIT/GAB 9/2016 Code 9991 was updated effective 1/1/2017 per Area Dental Request
 ;Addition of ADA-CDT Codes - 11 codes updated
ADDCDT5 ;EP
 D UPDATE^ADEUPD31(9999999.31,".01,.05,501,.06,,.02,8801,.09",1101,"?+1,","ADDADA^ADE6P311","SETX^ADE6P311")
 Q
 ;
SETX ;EP
 S ADEN=$P($P(ADEX,U),"D",2),$P(ADEX,U)=ADEN,$P(ADEX,U,6)=$TR($P(ADEX,U,6),"abcdefghijklmnopqrstuvwxyz","ABCDEFGHIJKLMNOPQRSTUVWXYZ")
 Q
 ;      
ADDADA ;    code^Level of care^RVU^Syn^^Nomen.^Mnem^Op Site Prompt / next line is the descriptor
 ;;D0414^9^0.50^LABCAS^^LABORATORY PROCESSING OF MICROBIAL SPECIMEN TO INCLUDE CULTURE AND SENSITIVITY STUDIES,PREPARATION AND TRANSMISSION OF WRITTEN REPORT^CAS^n
 ;;D0600^9^0.50^NIDP^^NON-IONIZING DIAGNOSTIC PROCEDURE CAPABLE OF QUANTIFYING,  MONITORING, AND RECORDING CHANGES IN STRUCTURE OF ENAMEL, DENTIN, AND CEMENTUM^NIDP^n
 ;;D1575^3^7.00^DSSUNI^^DISTAL SHOE SPACE MAINTAINER - FIXED - UNILATERAL^DSSMU^
 ;;FABRICATION AND DELIVERY OF FIXED APPLIANCE EXTENDING SUBGINGIVALLY AND DISTALLY TO GUIDE THE ERUPTION
 ;;OF THE FIRST PERMANENT MOLAR. DOES NOT INCLUDE ONGOING FOLLOW-UP OR ADJUSTMENTS, OR REPLACEMENT APPLIANCES,
 ;;ONCE THE TOOTH HAS ERUPTED.
 ;;D4346^3^3.00^FMSGING^^SCALING IN PRESENCE OF GENERALIZED MODERATE OR SEVERE GINGIVAL INFLAMMATION - FULL MOUTH,AFTER ORAL EVALUATION^FMSG^n
 ;;THE REMOVAL OF PLAQUE, CALCULUS AND STAINS FROM SUPRA- AND SUB-GINGIVAL TOOTH SURFACES WHEN THERE IS
 ;;GENERALIZED MODERATE OR SEVERE GINGIVAL INFLAMMATION IN THE ABSENCE OF PERIODONTITIS. IT IS INDICATED
 ;;FOR PATIENTS WHO HAVE SWOLLEN, INFLAMED GINGIVA, GENERALIZED SUPRABONY POCKETS, AND MODERATE TO SEVERE
 ;;BLEEDING ON PROBING.  SHOULD NOT BE REPORTED IN CONJUNCTION WITH PROPHYLAXIS, SCALING AND ROOT PLANING,
 ;;OR DEBRIDEMENT PROCEDURES.
 ;;D6081^3^1.00^IMPSCAL^^SCALING AND DEBRIDEMENT IN THE PRESENCE OF INFLAMMATION OR MUCOSITIS OF A SINGLE IMPLANT, INCLUDING CLEANING OF THE IMPLANT SURFACES, WITHOUT FLAP ENTRY AND CLOSURE^IMPS^
 ;;THIS PROCEDURE IS NOT PERFORMED IN CONJUNCTION WITH D1110 OR D4910.
 ;;D6085^5^6.00^PROIMPCRN^^PROVISIONAL IMPLANT CROWN^PIMC^
 ;;USED WHEN A PERIOD OF HEALING IS NECESSARY PRIOR TO FABRICATION AND PLACEMENT OF PERMANENT PROSTHETIC.
 ;;D9311^1^2.01^CONSMED^^CONSULTATION WITH A MEDICAL HEALTH CARE PROFESSIONAL^CMHC^n
 ;;TREATING DENTIST CONSULTS WITH A MEDICAL HEALTH CARE PROFESSIONAL CONCERNING MEDICAL ISSUES THAT MAY AFFECT
 ;;PATIENT'S PLANNED DENTAL TREATMENT.
 ;;D9991^1^0.51^DCMBARR^^DENTAL CASE MANAGEMENT - ADDRESSING APPOINTMENT COMPLIANCE BARRIERS^DCMA^n
 ;;INDIVIDUALIZED EFFORTS TO ASSIST A PATIENT TO MAINTAIN SCHEDULED APPOINTMENTS BY SOLVING TRANSPORTATION CHALLENGES OR OTHER BARRIERS.
 ;;D9992^1^1.00^DCMCARCO^^DENTAL CASE MANAGEMENT - CARE COORDINATION^DCMC^n
 ;;ASSISTING IN A PATIENTS DECISIONS REGARDING THE COORDINATION OF ORAL HEALTH CARE SERVICES ACROSS MULTIPLE PROVIDERS,
 ;;PROVIDER TYPES, SPECIALTY AREAS OF TREATMENT, HEALTH CARE SETTINGS, HEALTH CARE ORGANIZATIONS AND PAYMENT SYSTEMS.
 ;;THIS IS THE ADDITIONAL TIME AND RESOURCES EXPENDED TO PROVIDE EXPERIENCE OR EXPERTISE BEYOND THAT POSSESSED BY THE PATIENT. 
 ;;D9993^1^1.02^DCMMOTINT^^DENTAL CASE MANAGEMENT - MOTIVATIONAL INTERVIEWING^DCMM^n
 ;;PATIENT-CENTERED, PERSONALIZED COUNSELING USING METHODS SUCH AS MOTIVATIONAL INTERVIEWING (MI) TO IDENTIFY AND MODIFY BEHAVIORS
 ;;INTERFERING WITH POSITIVE ORAL HEALTH OUTCOMES. THIS IS A SEPARATE SERVICE FROM TRADITIONAL NUTRITIONAL OR TOBACCO COUNSELING.
 ;;D9994^1^1.00^DCMPATED^^DENTAL CASE MANAGEMENT - PATIENT EDUCATION TO IMPROVE ORAL HEALTH LITERACY^DCMP^n
 ;;INDIVIDUAL, CUSTOMIZED COMMUNICATION OF INFORMATION TO ASSIST THE PATIENT IN MAKING APPROPRIATE HEALTH DECISIONS DESIGNED TO
 ;;IMPROVE ORAL HEALTH LITERACY, EXPLAINED IN A MANNER ACKNOWLEDGING ECONOMIC CIRCUMSTANCES AND DIFFERENT CULTURAL BELIEFS, VALUES,
 ;;ATTITUDES, TRADITIONS AND LANGUAGE PREFERENCES, AND ADOPTING INFORMATION AND SERVICES TO THESE DIFFERENCES, WHICH REQUIRES THE
 ;;EXPENDITURE OF TIME AND RESOURCES BEYOND THAT OF AN ORAL EVALUATION OR CASE PRESENTATION.
 ;;***END***
