ADE6P331 ;IHS/OIT/GAB - ADE V6.0 PATCH 33 [ 10/12/2018  8:37 AM ]
 ;;6.0;ADE*6.0*33;;March 25, 1999;Build 53
 ;IHS/OIT/GAB 10/2018 Patch 33 ADA-CDT code updates for 2019
 ;Addition of ADA-CDT 2019 Codes; 13 new codes added
 ;New codes are shown below (up to D9961), codes below D9961 are for RVU updates
ADDCDT33 ;EP
 D UPDATE^ADEUPD33(9999999.31,".01,.05,501,.06,,.02,8801,.09",1101,"?+1,","ADDADA^ADE6P331","SETX^ADE6P331")
 Q
 ;
SETX ;EP
 S ADEN=$P($P(ADEX,U),"D",2),$P(ADEX,U)=ADEN,$P(ADEX,U,6)=$TR($P(ADEX,U,6),"abcdefghijklmnopqrstuvwxyz","ABCDEFGHIJKLMNOPQRSTUVWXYZ")
 Q
 ;
ADDADA ;    code^Level of care^RVU^Syn^^Nomen^Mnem^Op Site Prompt (either "n" or leave blank) / next line is the descriptor
 ;;D0412^1^1.30^BLD GLU TEST^^blood glucose level test - in-office using a glucose meter^BDGT^n
 ;;This procedure provides an immediate finding of a patients blood glucose level at the time of sample collection for the point-of-service analysis.
 ;;D1516^3^6.00^SPCMNTREM MAX^^space maintainer - fixed - bilateral, maxillary^SMRU^
 ;;D1517^3^6.00^SPCMNTREM MAN^^space maintainer - fixed - bilateral, mandibular^SMRL^
 ;;D1526^3^7.00^SPCMNTFIXD MAX^^space maintainer - removable - bilateral, maxillary^SMFU^
 ;;D1527^3^7.00^SPCMNTFIXD MAN^^space maintainer - removable - bilateral, mandibular^SMFL^
 ;;D5282^9^13.40^UNI MTL RPD MAX^^removable unilateral partial denture - one piece cast metal (including clasps and teeth), maxillary^UMRU^
 ;;D5283^9^13.40^UNI MTL RPD MAN^^removable unilateral partial denture - one piece cast metal (including clasps and teeth), mandibular^UMRL^
 ;;D5876^5^3.80^MTL SUBSTR CDN^^add metal substructure to acrylic full denture (per arch)^MSCD^
 ;;D9613^1^1.00^SUS REL DRUG^^infiltration of sustained release therapeutic drug - single or multiple sites^SRDG^n
 ;;Infiltration of a sustained release pharmacologic agent for long acting surgical site pain control.  Not for local anesthesia purposes.
 ;;D9944^5^10.00^OCCGRDHDFA^^occlusal guard - hard appliance, full arch^OGHF^
 ;;Removable dental appliance designed to minimize the effects of bruxism or other occlusal factors. Not to be reported for any type of sleep apnea, snoring or TMD appliances.
 ;;D9945^5^2.90^OCCGRDSTFA^^occlusal guard - soft appliance, full arch^OGSF^
 ;;Removable dental appliance designed to minimize the effects of bruxism or other occlusal factors. Not to be reported for any type of sleep apnea, snoring or TMD appliances.
 ;;D9946^5^5.00^OCCGRDHDPA^^occlusal guard - hard appliance, partial arch^OGHP^
 ;;Removable dental appliance designed to minimize the effects of bruxism or other occlusal factors. Provides only partial occlusal coverage such as anterior deprogrammer.
 ;;Not to be reported for any type of sleep apnea, snoring or TMD appliances.
 ;;D9961^4^0.00^DUP PT RCRD^^duplicate/copy patients records^DPTR^n
 ;;D9310^1^1.60^PROVIDE CONSULT^^CONSULTATION - DIAGNOSTIC SERVICE PROVIDED BY DENTIST OR PHYSICIAN OTHER THAN REQUESTING DENTIST OR PHYSICIAN^^n
 ;;D0369^5^22.00^MRICI^^MAXILLOFACIAL MRI CAPTURE AND INTERPRETATION^MRIC^n
 ;;D0370^5^7.40^USCI^^MAXILLOFACIAL ULTRASOUND CAPTURE AND INTERPRETATION^USCI^n
 ;;D5110^4^25.00^U. FULL DENTURE^^DENTURE - COMPLETE UPPER^F/U^n
 ;;D5120^4^25.00^L. FULL DENTURE^^DENTURE - COMPLETE LOWER^DC/F^n
 ;;D5213^4^30.00^U PARTIAL, A/CB^^UPPER PARTIAL, CAST FRAME, RESIN BASE^DP/S^n
 ;;D5214^4^30.00^L PARTIAL, A/CB^^LOWER PARTIAL, CAST FRAME, RESIN BASE^S/DP^n
 ;;D5223^5^30.00^IMMXPARTMET^^IMMEDIATE MAXILLARY PARTIAL DENTURE - CAST METAL FRAMEWORK WITH RESIN DENTURE BASES (INCLUDING ANY CONVENTIONAL CLASPS, RESTS AND TEETH)^IMMXPARTMET^
 ;;D5224^5^30.00^IMMDPARTMET^^IMMEDIATE MANDIBULAR PARTIAL DENTURE - CAST METAL FRAMEWORK WITH RESIN DENTURE BASES (INCLUDING ANY CONVENTIONAL CLASPS, RESTS AND TEETH)^IMMDPARTMET^
 ;;D5225^9^20.00^FLEX RPD MX^^MAXILLARY PARTIAL DENTURE - FLEXIBLE BASE (INCLUDING ANY CLASPS,RESTS AND TEETH)^^n
 ;;D5226^9^20.00^FLEX RPD MD^^MANDIBULAR PARTIAL DENTURE - FLEXIBLE BASE (INCLUDING ANY CLASPS,RESTS AND TEETH)^^n
 ;;D5987^6^20.00^COMMIS. SPLINT^^COMMISSURE SPLINT^^n
 ;;D6012^5^33.00^ENDOSTEAL IMP^^SURGICAL PLACEMENT OF INTERIM IMPLANT BODY FOR TRANSITIONAL PROSTHESIS: ENDOSTEAL IMPLANT^PLINIMP^
 ;;D6013^5^33.00^MINIIMPLANT^^SURGICAL PLACEMENT OF MINI IMPLANT^MINIIMPLANT^
 ;;D6051^5^5.70^INTABUT^^INTERIM ABUTMENT^INTABUT^
 ;;D6052^9^30.00^SEMIPRECABUT^^SEMI-PRECISION ATTACHMENT ABUTMENT^SEMIPRECABUT^
 ;;D6057^6^15.00^CUST ABUT^^CUSTOM FABRICATED ABUTMENT - INCLUDES PLACEMENT^CA^
 ;;D6081^3^3.50^IMPSCAL^^SCALING AND DEBRIDEMENT IN THE PRESENCE OF INFLAMMATION OR MUCOSITIS OF A SINGLE IMPLANT, INCLUDING CLEANING OF THE IMPLANT SURFACES, WITHOUT FLAP ENTRY AND CLOSURE^IMPS^
 ;;D6094^5^16.90^AB SUP CRN TI^^ABUTMENT SUPPORTED CROWN - (TITANIUM)^^
 ;;D6101^4^6.40^DEIMP^^DEBRIDEMENT OF A PERI-IMPLANT DEFECT OR DEFECTS SURROUNDING A SINGLE IMPLANT, AND SURFACE CLEANING OF THE EXPOSED IMPLANT SURFACES, INCLUDING FLAP ENTRY AND CLOSURE^DEIMP^
 ;;D6102^5^11.20^DEOSIMP^^DEBRIDEMENT AND OSSEOUS CONTOURING OF A PERI-IMPLANT DEFECT OR DEFECTS SURROUNDING A SINGLE IMPLANT AND INCLUDES SURFACE CLEANING OF THE EXPOSED IMPLANT SURFACES, INCLUDING FLAP ENTRY AND CLOSURE^DEOSIMP^
 ;;D6103^5^7.50^BGIMP^^BONE GRAFT FOR REPAIR OF PERI-IMPLANT DEFECT - DOES NOT INCLUDE FLAP ENTRY AND CLOSURE^BGIMP^
 ;;D6104^5^10.10^BGIMPPL^^BONE GRAFT AT TIME OF IMPLANT PLACEMENT^BGIMPPL^
 ;;D7295^5^15.00^HAR BONE GRAFT^^HARVEST OF BONE FOR USE IN AUTOGENOUS GRAFTING PROCEDURE^HBGRAFT^n
 ;;D7296^5^12.40^CORTICOTOMY,1-3^^CORTICOTOMY - ONE TO THREE TEETH OR TOOTH SPACES, PER QUADRANT^CORTICOTOMY,1-3^
 ;;D7297^5^16.00^CORTICOTOMY,4+^^CORTICOTOMY - FOUR OR MORE TEETH OR TOOTH SPACES, PER QUADRANT^CORTICOTOMY,4+^
 ;;D7490^6^150.00^RAD RESECT MAND^^RADICAL RESECTION OF MAXILLA OR MANDIBLE^^
 ;;D7511^1^4.40^ID IO^^INCISION AND DRAINAGE OF ABSCESS - INTRAORAL SOFT TISSUE - COMPLICATED (INCLUDES DRAINAGE OF MULTIPLE FASCIAL SPACES)^^n
 ;;D7671^1^38.00^ALVEOLUS - OPEN REDUCTION^^ALVEOLUS - OPEN REDUCTION, MAY INCLUDE STABILIZATION OF TEETH^^
 ;;D7771^1^23.50^ALVEOLUS, CLOSED REDUCTION^^ALVEOLUS, CLOSED REDUCTION STABILIZATION OF TEETH^^
 ;;D7820^1^9.00^RED TMJ DISLOC^^CLOSED REDUCTION OF DISLOCATION^^n
 ;;D7856^6^80.00^^^MYOTOMY^^n
 ;;D7881^1^4.50^OCCORTHOTICADJ^^OCCLUSAL ORTHOTIC DEVICE ADJUSTMENT^OCCORTHOTICADJ^
 ;;D7910^1^4.20^SUTURE WOUNDS^^SUTURE OF RECENT SMALL WOUNDS UP TO 5 CM^^n
 ;;D7953^5^19.00^BRG^^BONE REPLACEMENT GRAFT FOR RIDGE PRESERVATION - PER SITE^^
 ;;D7970^3^10.00^EXCISE HYPER T.^^EXCISION HYPERPLASTIC TISSUE - PER ARCH^^
 ;;D7971^1^4.00^EXCISE GINGIVA^^EXCISION OF PERICORONAL GINGIVA^^
 ;;D7979^5^10.00^N-SSIALOLITHOTH^^NON-SURGICAL SIALOLITHOTOMY^N-SSIALOLITHOTH^n
 ;;D7995^6^15.00^SYNT GRFT/FACL^^SYNTHETIC GRAFT - MANDIBLE OR FACIAL BONES^^n
 ;;D7996^6^15.00^IMPLNT AUGMNT^^IMPLANT-MANDIBLE FOR AUGMENTATION PURPOSES (EXLUDING ALVEOLAR RIDGE),BY REPORT^^n
 ;;D7997^3^6.00^APP REM^^APPLIANCE REMOVAL (NOT BY DENTIST WHO PLACED APPLIANCE), INCLUDES REMOVAL OF ARCHBAR^AR^
 ;;D8670^4^3.60^ORTHO CHK VISIT^^PERIODIC ORTHODONTIC TREATMENT VISIT^CFUV^n
 ;;D8690^6^3.30^ORTHO FEE (ALT)^^ORTHO TX (ALT. BILLING TO A CONTRACT FEE)^^n
 ;;D9221^6^3.00^GEN ANES, add.^^DEEP SEDATION/GENERAL ANESTHESIA - EACH ADDITIONAL 15 MINUTES^^n
 ;;D9230^5^2.00^N2O ANALGESIA^^INHALATION OF NITROUS OXIDE / ANALGESIA, ANXIOLYSIS^^n
 ;;***END***
